import Head from 'next/head'
import  HomePage  from './Component/HomePage'




export default function Home() {
  return (
    <div >
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage/>
    </div>
  )
}
